# docker-compose -f docker-compose-be.yml up -d
# docker-compose -f docker-compose-be.yml down
version: '3'

services:
  backend:
    image: yancarlos18/springboot-sqlserver:1.0   # cambiar por tu usuario de dockerhub
    container_name: springboot-sqlserver
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SERVER_URL=http://localhost:5000
      - DATABASE_URL=jdbc:sqlserver://sql-server:1433;databaseName=DF_BerryControl;encrypt=true;trustServerCertificate=true
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=Yancarlos123!
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
    networks:
      - my-network

# CONSUMIR UNA RED EXISTENTE CREADA POR OTRO COMPOSE
networks:
  my-network:
    external: true   # usa la red creada por el compose de la base de datos

# CREAR UNA RED EN ESTE COMPOSE PARA QUE SEA COMPARTIDA
#networks:
#  my-network:
#    name: my-network   # red compartida, visible desde ambos compose
#    driver: bridge

# Ruta para acceder a Swagger UI: http://localhost:5000/swagger-ui.html